text = """
the king loved the queen and the queen loved the king
the king loved playing cricket in the garden
the queen loved playing chess in the garden
the king and the queen walked in the garden
the king loved the kingdom and the people loved the king
"""
words = text.lower().split()
print(f"The length of the string:{len(words)}")
print(f"The first 10 of the string:{words[:10]}")
pair_counts = {}

for i in range(len(words)-1):
    curr_word = words[i]
    next_word = words[i+1]

    if curr_word not in pair_counts:
        pair_counts[curr_word] = {}

    if next_word not in pair_counts[curr_word]:
        pair_counts[curr_word][next_word]=1

pair_counts[curr_word][next_word]+=1

print("after the:", pair_counts["the"])
print("after king:", pair_counts["king"])
print("after loved:", pair_counts["loved"])

pair_probs = {}

for curr_word in pair_counts:
    pair_probs[curr_word] = {}
    total = sum(pair_counts[curr_word].values())

    for next_word in pair_counts[curr_word]:
        pair_probs[curr_word][next_word] = pair_counts[curr_word][next_word] / total

print("\n Probabilities after the ")
for word, probs in sorted(pair_probs["king"].items(), key = lambda x: -x [1]):
    print(f"{word} : {probs : .1%}")
    

import random

def generate_token(start_word, num_words = 20):
    curr_word = start_word
    output = [curr_word]

    for _ in range(num_words):

        if curr_word not in pair_probs:
            break

        options = list(pair_probs[curr_word].keys())
        probabilities = list(pair_probs[curr_word].values())

        next_word = random.choices(options, weights = probabilities, k=1)[0]

        output.append(next_word)
        curr_word =  next_word

    return " ".join(output)
print("Text generated by bygram model")
for i in range(5):
    print(f" {i+1} {generate_token('the', 5)}")
